enable_eth_rpc = true
eth_host = "0.0.0.0"
eth_port = "9092"


# [Module:EventsWatcher]
enable_event_watcher = true
# note: need websocket rpc to listen to the L1 event
l1_client_address = ""                      # use your own infura address
l2_client_address = "http://localhost:9092"
parentlayer_contract_address = ""
childlayer_contract_address = ""
opreator_private_key = ""
