# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/docs/**'
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/docs/**'
      - '**/README.md'

jobs:

  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Run Makefile check-mod-tidy
        run: make check-mod-tidy
      - name: Build
        run: make build
      - name: Test
        run: make transfer_test
