{
 "title": "Reddio-Dev",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_heap_sys_bytes", "legendFormat": "{{instance}}-heap-sys" },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"$instance\", job=\"ekuiper\"}",
     "legendFormat": "{{instance}}-heap-alloc"
    },
    { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "{{instance}}-heap-inuse" },
    { "expr": "go_memstats_heap_idle_bytes", "legendFormat": "{{instance}}-heap-idle" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Txn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Txn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(reddio_txn_total_count[1m])",
     "legendFormat": "txn-{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "Txn Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(reddio_txn_execute_duration_seconds_bucket[1m])))",
     "legendFormat": "txn_P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(reddio_txn_execute_duration_seconds_bucket[1m])))",
     "legendFormat": "txn_P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(reddio_txn_execute_duration_seconds_bucket[1m])))",
     "legendFormat": "txn_P90"
    }
   ]
  },
  { "title": "Batch Txn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Batch Txn Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(reddio_batch_txn_total_count[1m])",
     "legendFormat": "txn-{{instance}}-{{type}}"
    }
   ]
  },
  {
   "title": "Batch Txn Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(reddio_batch_txn_execute_duration_seconds_bucket[1m])))",
     "legendFormat": "txn_P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(reddio_batch_txn_execute_duration_seconds_bucket[1m])))",
     "legendFormat": "txn_P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(reddio_batch_txn_execute_duration_seconds_bucket[1m])))",
     "legendFormat": "txn_P90"
    }
   ]
  }
 ]
}